// <auto-generated />
using System;
using System.Collections.Generic;
using LeWiK.Store.App.Common.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LeWiK.Store.App.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20260702010953_OrdersAndCustomers")]
    partial class OrdersAndCustomers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_products");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_products_tenant_id");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.HasKey("Id")
                        .HasName("pk_product_options");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_options_product_id");

                    b.ToTable("product_options", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.Property<Guid>("ProductOptionId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_id");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_product_option_values");

                    b.HasIndex("ProductOptionId")
                        .HasDatabaseName("ix_product_option_values_product_option_id");

                    b.ToTable("product_option_values", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductVariant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Price", "LeWiK.Store.App.Catalog.Domain.ProductVariant.Price#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_product_variants");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_product_variants_product_id");

                    b.ToTable("product_variants", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.PurchaseLimit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int?>("MaxPerCustomer")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_customer");

                    b.Property<int?>("MaxPerOrder")
                        .HasColumnType("integer")
                        .HasColumnName("max_per_order");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("scope");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<int?>("WindowDays")
                        .HasColumnType("integer")
                        .HasColumnName("window_days");

                    b.HasKey("Id")
                        .HasName("pk_purchase_limits");

                    b.HasIndex("TenantId", "Scope", "TargetId")
                        .IsUnique()
                        .HasDatabaseName("ix_purchase_limits_tenant_id_scope_target_id");

                    b.ToTable("purchase_limits", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.VariantOptionValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ProductOptionValueId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_option_value_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.HasKey("Id")
                        .HasName("pk_variant_option_values");

                    b.HasIndex("ProductOptionValueId")
                        .HasDatabaseName("ix_variant_option_values_product_option_value_id");

                    b.HasIndex("ProductVariantId", "ProductOptionValueId")
                        .IsUnique()
                        .HasDatabaseName("ix_variant_option_values_product_variant_id_product_option_val");

                    b.ToTable("variant_option_values", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Customers.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<bool>("IsRegistered")
                        .HasColumnType("boolean")
                        .HasColumnName("is_registered");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("phone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_tenant_id_email");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Inventory.Domain.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("available_quantity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer")
                        .HasColumnName("reserved_quantity");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_inventories");

                    b.HasIndex("TenantId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ix_inventories_tenant_id_product_variant_id");

                    b.ToTable("inventories", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Inventory.Domain.StockMovement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InventoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("inventory_id");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer")
                        .HasColumnName("quantity");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("reason");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_stock_movements");

                    b.HasIndex("InventoryId")
                        .HasDatabaseName("ix_stock_movements_inventory_id");

                    b.ToTable("stock_movements", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Orders.Domain.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<decimal>("DepositDueAmount")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("deposit_due_amount");

                    b.Property<string>("FulfillmentStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fulfillment_status");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("paid_amount");

                    b.Property<string>("PaymentStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("payment_status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("total_amount");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_orders_tenant_id");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Orders.Domain.OrderLine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("IsPreorder")
                        .HasColumnType("boolean")
                        .HasColumnName("is_preorder");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name_snapshot");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<int>("QtyFulfilled")
                        .HasColumnType("integer")
                        .HasColumnName("qty_fulfilled");

                    b.Property<int>("QtyOrdered")
                        .HasColumnType("integer")
                        .HasColumnName("qty_ordered");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("sku");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "UnitPrice", "LeWiK.Store.App.Orders.Domain.OrderLine.UnitPrice#Money", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<decimal>("Amount")
                                .HasPrecision(14, 4)
                                .HasColumnType("numeric(14,4)")
                                .HasColumnName("unit_price_amount");

                            b1.Property<string>("Currency")
                                .IsRequired()
                                .HasMaxLength(3)
                                .HasColumnType("character varying(3)")
                                .HasColumnName("unit_price_currency");
                        });

                    b.HasKey("Id")
                        .HasName("pk_order_lines");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_lines_order_id");

                    b.ToTable("order_lines", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Preorders.Domain.Preorder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer")
                        .HasColumnName("capacity");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DepositType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("deposit_type");

                    b.Property<decimal>("DepositValue")
                        .HasPrecision(14, 4)
                        .HasColumnType("numeric(14,4)")
                        .HasColumnName("deposit_value");

                    b.Property<Guid>("ProductVariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_variant_id");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<int>("SoldCount")
                        .HasColumnType("integer")
                        .HasColumnName("sold_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_preorders");

                    b.HasIndex("TenantId", "ProductVariantId")
                        .IsUnique()
                        .HasDatabaseName("ix_preorders_tenant_id_product_variant_id");

                    b.ToTable("preorders", (string)null);
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductOption", b =>
                {
                    b.HasOne("LeWiK.Store.App.Catalog.Domain.Product", null)
                        .WithMany("Options")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_options_products_product_id");
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductOptionValue", b =>
                {
                    b.HasOne("LeWiK.Store.App.Catalog.Domain.ProductOption", null)
                        .WithMany("Values")
                        .HasForeignKey("ProductOptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_option_values_product_options_product_option_id");
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductVariant", b =>
                {
                    b.HasOne("LeWiK.Store.App.Catalog.Domain.Product", null)
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_product_variants_products_product_id");
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.VariantOptionValue", b =>
                {
                    b.HasOne("LeWiK.Store.App.Catalog.Domain.ProductOptionValue", null)
                        .WithMany()
                        .HasForeignKey("ProductOptionValueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variant_option_values_product_option_values_product_option_");

                    b.HasOne("LeWiK.Store.App.Catalog.Domain.ProductVariant", null)
                        .WithMany("OptionValues")
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_variant_option_values_product_variants_product_variant_id");
                });

            modelBuilder.Entity("LeWiK.Store.App.Inventory.Domain.StockMovement", b =>
                {
                    b.HasOne("LeWiK.Store.App.Inventory.Domain.InventoryItem", null)
                        .WithMany("Movements")
                        .HasForeignKey("InventoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stock_movements_inventories_inventory_id");
                });

            modelBuilder.Entity("LeWiK.Store.App.Orders.Domain.OrderLine", b =>
                {
                    b.HasOne("LeWiK.Store.App.Orders.Domain.Order", null)
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_lines_orders_order_id");
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.Product", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductOption", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("LeWiK.Store.App.Catalog.Domain.ProductVariant", b =>
                {
                    b.Navigation("OptionValues");
                });

            modelBuilder.Entity("LeWiK.Store.App.Inventory.Domain.InventoryItem", b =>
                {
                    b.Navigation("Movements");
                });

            modelBuilder.Entity("LeWiK.Store.App.Orders.Domain.Order", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
